In [1]:
# Cell 1
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
# Cell 2
from src.extract import run_extraction

In [3]:
import pandas as pd

drivers_df = pd.read_csv("../data/raw/F1_drivers.csv")
drivers_df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,Oscar Piastri,Australia,"[2023, 2024, 2025, 2026]",0,73,71,6,9,27,9,...,NaN,2020,0.082192,0.972603,0.123288,0.369863,0.123288,11.232877,4,False
1,Alexander Albon,Thailand,"[2019, 2020, 2022, 2023, 2024, 2025, 2026]",0,133,130,0,0,2,1,...,NaN,2020,0.000000,0.977444,0.000000,0.015038,0.007519,2.353383,7,False
2,Lando Norris,United Kingdom,"[2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]",1,155,154,16,11,44,18,...,[2025],2020,0.103226,0.993548,0.070968,0.283871,0.116129,9.387097,8,True
3,George Russell,United Kingdom,"[2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]",0,155,155,8,6,26,11,...,NaN,2020,0.051613,1.000000,0.038710,0.167742,0.070968,7.070968,8,False
4,Charles Leclerc,Monaco,"[2018, 2019, 2020, 2021, 2022, 2023, 2024, 202...",0,176,174,27,8,52,11,...,NaN,2020,0.153409,0.988636,0.045455,0.295455,0.062500,9.778409,9,False

In [4]:
print(drivers_df.dtypes)
print("---")
print(drivers_df.isnull().sum())

Driver                    str
Nationality               str
Seasons                   str
Championships           int64
Race_Entries            int64
Race_Starts             int64
Pole_Positions          int64
Race_Wins               int64
Podiums                 int64
Fastest_Laps            int64
Points                float64
Active                   bool
Championship Years        str
Decade                  int64
Pole_Rate             float64
Start_Rate            float64
Win_Rate              float64
Podium_Rate           float64
FastLap_Rate          float64
Points_Per_Entry      float64
Years_Active            int64
Champion                 bool
dtype: object
---
Driver                  0
Nationality             0
Seasons                 0
Championships           0
Race_Entries            0
Race_Starts             0
Pole_Positions          0
Race_Wins               0
Podiums                 0
Fastest_Laps            0
Points                  0
Active                  0
Championship Years    841
Decade                  0
Pole_Rate               0
Start_Rate              0
Win_Rate                0
Podium_Rate             0
FastLap_Rate            0
Points_Per_Entry        0
Years_Active            0
Champion                0
dtype: int64

In [5]:
print(drivers_df[drivers_df.astype(str).apply(lambda col: col.str.contains(r'\\N', na=False)).any(axis=1)].head())

Empty DataFrame
Columns: [Driver, Nationality, Seasons, Championships, Race_Entries, Race_Starts, Pole_Positions, Race_Wins, Podiums, Fastest_Laps, Points, Active, Championship Years, Decade, Pole_Rate, Start_Rate, Win_Rate, Podium_Rate, FastLap_Rate, Points_Per_Entry, Years_Active, Champion]
Index: []

[0 rows x 22 columns]

In [6]:
import sys, os
sys.path.append(os.path.abspath(".."))

from src.transform import clean_nulls

drivers_clean = clean_nulls(drivers_df)
print(drivers_clean.isnull().sum())

Driver                  0
Nationality             0
Seasons                 0
Championships           0
Race_Entries            0
Race_Starts             0
Pole_Positions          0
Race_Wins               0
Podiums                 0
Fastest_Laps            0
Points                  0
Active                  0
Championship Years    841
Decade                  0
Pole_Rate               0
Start_Rate              0
Win_Rate                0
Podium_Rate             0
FastLap_Rate            0
Points_Per_Entry        0
Years_Active            0
Champion                0
dtype: int64

In [7]:
from src.transform import parse_lap_time

test_cases = ["1:23.456", "23.456", "\\N", None, "", "0:59.999"]
for t in test_cases:
    print(t, "->", parse_lap_time(t))

1:23.456 -> 83456
23.456 -> 23456
\N -> nan
None -> nan
 -> nan
0:59.999 -> 59999

In [8]:
print(drivers_df.columns.tolist())

['Driver', 'Nationality', 'Seasons', 'Championships', 'Race_Entries', 'Race_Starts', 'Pole_Positions', 'Race_Wins', 'Podiums', 'Fastest_Laps', 'Points', 'Active', 'Championship Years', 'Decade', 'Pole_Rate', 'Start_Rate', 'Win_Rate', 'Podium_Rate', 'FastLap_Rate', 'Points_Per_Entry', 'Years_Active', 'Champion']

In [10]:
import pandas as pd

drivers_df = pd.read_csv("../data/raw/F1_drivers.csv")
print(drivers_df.columns.tolist())

['Driver', 'Nationality', 'Seasons', 'Championships', 'Race_Entries', 'Race_Starts', 'Pole_Positions', 'Race_Wins', 'Podiums', 'Fastest_Laps', 'Points', 'Active', 'Championship Years', 'Decade', 'Pole_Rate', 'Start_Rate', 'Win_Rate', 'Podium_Rate', 'FastLap_Rate', 'Points_Per_Entry', 'Years_Active', 'Champion']

In [11]:
pd.set_option('display.max_columns', None)
drivers_df.head(10)

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,Points,Active,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,Oscar Piastri,Australia,"[2023, 2024, 2025, 2026]",0,73,71,6,9,27,9,820.0,True,NaN,2020,0.082192,0.972603,0.123288,0.369863,0.123288,11.232877,4,False
1,Alexander Albon,Thailand,"[2019, 2020, 2022, 2023, 2024, 2025, 2026]",0,133,130,0,0,2,1,313.0,True,NaN,2020,0.000000,0.977444,0.000000,0.015038,0.007519,2.353383,7,False
2,Lando Norris,United Kingdom,"[2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]",1,155,154,16,11,44,18,1455.0,True,[2025],2020,0.103226,0.993548,0.070968,0.283871,0.116129,9.387097,8,True
3,George Russell,United Kingdom,"[2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]",0,155,155,8,6,26,11,1096.0,True,NaN,2020,0.051613,1.000000,0.038710,0.167742,0.070968,7.070968,8,False
4,Charles Leclerc,Monaco,"[2018, 2019, 2020, 2021, 2022, 2023, 2024, 202...",0,176,174,27,8,52,11,1721.0,True,NaN,2020,0.153409,0.988636,0.045455,0.295455,0.062500,9.778409,9,False
5,Pierre Gasly,France,"[2017, 2018, 2019, 2020, 2021, 2022, 2023, 202...",0,181,180,0,1,5,3,473.0,True,NaN,2020,0.000000,0.994475,0.005525,0.027624,0.016575,2.613260,10,False
6,Lance Stroll,Canada,"[2017, 2018, 2019, 2020, 2021, 2022, 2023, 202...",0,196,192,1,0,3,0,325.0,True,NaN,2020,0.005102,0.979592,0.000000,0.015306,0.000000,1.658163,10,False
7,Esteban Ocon,France,"[2016, 2017, 2018, 2020, 2021, 2022, 2023, 202...",0,183,183,0,1,4,1,484.0,True,NaN,2020,0.000000,1.000000,0.005464,0.021858,0.005464,2.644809,10,False
8,Carlos Sainz Jr.,Spain,"[2015, 2016, 2017, 2018, 2019, 2020, 2021, 202...",0,236,232,6,4,29,4,1338.5,True,NaN,2020,0.025424,0.983051,0.016949,0.122881,0.016949,5.671610,12,False
9,Max Verstappen,Netherlands,"[2015, 2016, 2017, 2018, 2019, 2020, 2021, 202...",4,236,236,48,71,127,37,3456.5,True,"[2021, 2022, 2023, 2024]",2020,0.203390,1.000000,0.300847,0.538136,0.156780,14.646186,12,True

In [12]:
print(drivers_df.dtypes)
print("---")
print(drivers_df.isnull().sum())
print("---")
print(drivers_df.shape)

Driver                    str
Nationality               str
Seasons                   str
Championships           int64
Race_Entries            int64
Race_Starts             int64
Pole_Positions          int64
Race_Wins               int64
Podiums                 int64
Fastest_Laps            int64
Points                float64
Active                   bool
Championship Years        str
Decade                  int64
Pole_Rate             float64
Start_Rate            float64
Win_Rate              float64
Podium_Rate           float64
FastLap_Rate          float64
Points_Per_Entry      float64
Years_Active            int64
Champion                 bool
dtype: object
---
Driver                  0
Nationality             0
Seasons                 0
Championships           0
Race_Entries            0
Race_Starts             0
Pole_Positions          0
Race_Wins               0
Podiums                 0
Fastest_Laps            0
Points                  0
Active                  0
Championship Years    841
Decade                  0
Pole_Rate               0
Start_Rate              0
Win_Rate                0
Podium_Rate             0
FastLap_Rate            0
Points_Per_Entry        0
Years_Active            0
Champion                0
dtype: int64
---
(876, 22)

In [13]:
mask = drivers_df.astype(str).apply(lambda col: col.str.contains(r'\\N', na=False)).any(axis=1)
print(f"Rows containing \\N: {mask.sum()}")
drivers_df[mask].head()

Rows containing \N: 0

Empty DataFrame
Columns: [Driver, Nationality, Seasons, Championships, Race_Entries, Race_Starts, Pole_Positions, Race_Wins, Podiums, Fastest_Laps, Points, Active, Championship Years, Decade, Pole_Rate, Start_Rate, Win_Rate, Podium_Rate, FastLap_Rate, Points_Per_Entry, Years_Active, Champion]
Index: []